# Generated by Django 2.1.7 on 2019-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_view1', 'Can view View 1'), ('can_view_view2', 'Can view View 2')),
            },
        ),
    ]
